### ISSUE TITLE
Logging amount of remote <-> local IO?

### ISSUE THREAD

**Issue by jberryman** [Overv/outrun#15]
I'd like to use `outrun` for a fairly complex task, where I want to ensure that IO across the local/remote boundary isn't a bottleneck (and where I'm not sure where and whether a lot of that kind of IO might be happening).

My thought in evaluating `outrun` in this context was to modify `outrun` to log this proxied IO to a file, via a new optional flag. So I'm wondering:

- is this a good idea, or is there some trivial way to do this externally to `outrun` (I suppose if I could log the amount of data going over the ssh connection that would be sufficient... but wouldn't support debugging)
- any thoughts on what sort of design you'd consider merging if I made a PR?

Thanks! This is a really cool project

**Comment by Overv** [comment]
You can run outrun with the `--debug` flag to see all RPC calls that are being made (primary for IO). That's what I used to monitor behavior during development. However, that will only show you the operations occurring and not necessarily the volume of IO.

It may be useful to provide more insight in some other way, either through a new flag or by extending the existing debug info, so I'd be interested in hearing your ideas about what kind of info you'd log to such a file.

**Comment by jberryman** [comment]
Thanks! I should have held off posting before actually trying that...
